USE quiz_db;

INSERT INTO questions (question_text, option_a, option_b, option_c, option_d, correct_answer, category, difficulty) VALUES
('What is the capital of Italy?', 'Rome', 'Milan', 'Venice', 'Florence', 'A', 'Geography', 'Easy'),
('Which planet is closest to the Sun?', 'Venus', 'Mercury', 'Mars', 'Earth', 'B', 'Science', 'Easy'),
('Who painted the Starry Night?', 'Pablo Picasso', 'Vincent van Gogh', 'Claude Monet', 'Salvador Dali', 'B', 'Art', 'Medium'),
('What is the largest continent?', 'Africa', 'North America', 'Asia', 'Europe', 'C', 'Geography', 'Easy'),
('In which year did World War I begin?', '1912', '1914', '1916', '1918', 'B', 'History', 'Medium'),
('What is the speed of light?', '300,000 km/s', '150,000 km/s', '450,000 km/s', '200,000 km/s', 'A', 'Science', 'Medium'),
('Which programming language is known as the "mother of all languages"?', 'C', 'Assembly', 'FORTRAN', 'COBOL', 'A', 'Technology', 'Medium'),
('What is the currency of Japan?', 'Yuan', 'Won', 'Yen', 'Ringgit', 'C', 'General', 'Easy'),
('How many bones are in the human body?', '196', '206', '216', '186', 'B', 'Science', 'Medium'),
('Who wrote "1984"?', 'Aldous Huxley', 'George Orwell', 'Ray Bradbury', 'H.G. Wells', 'B', 'Literature', 'Medium'),
('What is the smallest country in the world?', 'Monaco', 'Vatican City', 'San Marino', 'Liechtenstein', 'B', 'Geography', 'Medium'),
('Which element has the symbol "Fe"?', 'Fluorine', 'Iron', 'Francium', 'Fermium', 'B', 'Science', 'Easy'),
('What is 12 × 12?', '124', '144', '134', '154', 'B', 'Math', 'Easy'),
('Who discovered penicillin?', 'Louis Pasteur', 'Alexander Fleming', 'Marie Curie', 'Jonas Salk', 'B', 'Science', 'Medium'),
('What is the capital of Australia?', 'Sydney', 'Melbourne', 'Canberra', 'Brisbane', 'C', 'Geography', 'Medium'),
('Which ocean is the deepest?', 'Atlantic', 'Indian', 'Pacific', 'Arctic', 'C', 'Geography', 'Easy'),
('What does HTML stand for?', 'HyperText Markup Language', 'HighText Machine Language', 'HyperText Machine Language', 'HighText Markup Language', 'A', 'Technology', 'Easy'),
('Who was the first person to walk on the moon?', 'Buzz Aldrin', 'Neil Armstrong', 'Yuri Gagarin', 'John Glenn', 'B', 'History', 'Easy'),
('What is the largest organ in the human body?', 'Liver', 'Brain', 'Skin', 'Heart', 'C', 'Science', 'Easy'),
('Which country is known as the Land of the Rising Sun?', 'China', 'Japan', 'Thailand', 'South Korea', 'B', 'Geography', 'Easy'),
('What is the boiling point of water in Celsius?', '90°C', '100°C', '110°C', '120°C', 'B', 'Science', 'Easy'),
('Who invented the telephone?', 'Thomas Edison', 'Nikola Tesla', 'Alexander Graham Bell', 'Guglielmo Marconi', 'C', 'History', 'Medium'),
('What is the capital of Canada?', 'Toronto', 'Vancouver', 'Ottawa', 'Montreal', 'C', 'Geography', 'Medium'),
('Which gas makes up most of Earth''s atmosphere?', 'Oxygen', 'Nitrogen', 'Carbon Dioxide', 'Hydrogen', 'B', 'Science', 'Medium'),
('What is the square root of 169?', '11', '12', '13', '14', 'C', 'Math', 'Easy'),
('Who wrote "Harry Potter"?', 'J.R.R. Tolkien', 'J.K. Rowling', 'C.S. Lewis', 'Roald Dahl', 'B', 'Literature', 'Easy'),
('What is the largest desert in the world?', 'Sahara', 'Arabian', 'Gobi', 'Antarctic', 'D', 'Geography', 'Hard'),
('Which planet is known for its rings?', 'Jupiter', 'Saturn', 'Uranus', 'Neptune', 'B', 'Science', 'Easy'),
('What does CPU stand for?', 'Central Processing Unit', 'Computer Personal Unit', 'Central Program Utility', 'Computer Processing Unit', 'A', 'Technology', 'Easy'),
('In which city is the Eiffel Tower located?', 'London', 'Berlin', 'Paris', 'Rome', 'C', 'Geography', 'Easy'),
('What is the freezing point of water in Fahrenheit?', '0°F', '32°F', '100°F', '212°F', 'B', 'Science', 'Easy'),
('Who painted the Mona Lisa?', 'Michelangelo', 'Raphael', 'Leonardo da Vinci', 'Donatello', 'C', 'Art', 'Easy'),
('What is the largest planet in our solar system?', 'Saturn', 'Jupiter', 'Neptune', 'Uranus', 'B', 'Science', 'Easy'),
('Which country invented pizza?', 'Greece', 'Italy', 'France', 'Spain', 'B', 'General', 'Easy'),
('What is 25% of 200?', '25', '50', '75', '100', 'B', 'Math', 'Easy'),
('Who is known as the father of computers?', 'Alan Turing', 'Charles Babbage', 'Bill Gates', 'Steve Jobs', 'B', 'Technology', 'Medium'),
('What is the longest river in the world?', 'Amazon', 'Nile', 'Yangtze', 'Mississippi', 'B', 'Geography', 'Medium'),
('Which vitamin is produced when skin is exposed to sunlight?', 'Vitamin A', 'Vitamin C', 'Vitamin D', 'Vitamin E', 'C', 'Science', 'Medium'),
('What is the capital of Spain?', 'Barcelona', 'Madrid', 'Seville', 'Valencia', 'B', 'Geography', 'Easy'),
('How many continents are there?', '5', '6', '7', '8', 'C', 'Geography', 'Easy');
